In [3]:
!pip install -U sentence-transformers

  Using cached sentence-transformers-2.2.0.tar.gz (79 kB)
  Using cached transformers-4.16.2-py3-none-any.whl (3.5 MB)
  Using cached sentencepiece-0.1.96-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
  Using cached huggingface_hub-0.4.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 596 kB 5.1 MB/s 
     |████████████████████████████████| 6.5 MB 48.9 MB/s 
     |████████████████████████████████| 895 kB 62.3 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.0-py3-none-any.whl size=120747 sha256=c012334bafe39e879f75cdb8042324cf4e766baedcd3b7841d000361af2ae4b7
  Stored in directory: /root/.cache/pip/wheels/83/c0/df/b6873ab7aac3f2465aa9144b6b4c41c4391cfecc027c8b07e7
Successfully built sentence-transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [4]:
import torch 
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("vinai/phobert-base")

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.60k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/557 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/543M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/895k [00:00<?, ?B/s]

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/vinai_phobert-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.decoder.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [5]:
lst_all = []

In [6]:
with open("/content/corpus.txt", "r") as f:
  f_contents = f.readlines()
  lst_all.append(f_contents)

In [7]:
lst_all[0][2]

'Bản sao y bản chính, bản trích sao, bản sao lục được hiểu khác nhau như thế nào theo Quy chế Công tác văn thư của Tập đoàn Dầu khí Việt Nam? <0000> Theo “Quy chế Công tác văn thư của Tập đoàn Dầu khí Việt Nam” của Tập đoàn Dầu khí Việt Nam • Tại Khoản 13, Điều 2 Quy định: “Bản sao y bản chính: bản sao đầy đủ, chính xác nội dung của văn bản, được trình bày theo thể thức quy định. Bản sao y bản chính phải được thực hiện từ bản chính.” • Tại Khoản 14, Điều 2 Quy định: “Bản trích sao: bản sao một phần nội dung của văn bản, được trình bày theo thể thức quy định. Bản trích sao phải được thực hiện từ bản chính.” • Tại Khoản 15, Điều 2 Quy định: “Bản sao lục: bản sao đầy đủ, chính xác nội dung của văn bản, được thực hiện từ bản sao y bản chính và trình bày theo thể thức quy định.”\n'

In [8]:
ques = []

In [9]:
ans = []

In [10]:
len(lst_all[0])

261

In [11]:
for i in range(0, len(lst_all[0])-1):
    a = lst_all[0][i].split("<0000>")
    ques.append(a[0])
    ques[i] = ques[i].strip()
    ans.append(a[1])

In [12]:
ques[5:10]

['Một cán bộ nhân viên Ban Tài chính Kế toán PVN được bố trí kiêm nhiệm làm văn thư cho Ban đó sẽ được bồi dưỡng nghiệp vụ văn thư, lưu trữ  đúng không?',
 'Kinh phí cho công tác văn thư trong Cơ quan PVN được lấy từ nguồn kinh phí nào?',
 'Ai có trách nhiệm lập dự trù kinh phí cho hoạt động văn thư trong Cơ quan PVN?',
 'Báo cáo thống kê cơ sở công tác văn thư của Cơ quan PVN được Văn phòng PVN tổng hợp gửi về cơ quan nhà nước nào?',
 'Khi được phép bằng miệng của Lãnh đạo PVN, cán bộ văn thư có thể được cung cấp thông tin, tài liệu nội bộ chưa công bố cho những người thuộc Ban/Văn phòng khác đúng không?']

In [13]:
# Install the vncorenlp python wrapper
!pip3 install vncorenlp

# Download VnCoreNLP-1.1.1.jar & its word segmentation component (i.e. RDRSegmenter) 
!mkdir -p vncorenlp/models/wordsegmenter
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/vi-vocab
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/wordsegmenter.rdr
!mv VnCoreNLP-1.1.1.jar vncorenlp/ 
!mv vi-vocab vncorenlp/models/wordsegmenter/
!mv wordsegmenter.rdr vncorenlp/models/wordsegmenter/

     |████████████████████████████████| 2.6 MB 5.4 MB/s 
  Created wheel for vncorenlp: filename=vncorenlp-1.0.3-py3-none-any.whl size=2645951 sha256=14a9a662e21b845374f03ae313af6e7c28ce5587b847d9241902688725dadbad
  Stored in directory: /root/.cache/pip/wheels/0c/d8/f2/d28d97379b4f6479bf51247c8dfd57fa00932fa7a74b6aab29
Successfully built vncorenlp
--2022-03-03 13:09:33--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27412575 (26M) [application/octet-stream]
Saving to: ‘VnCoreNLP-1.1.1.jar’

VnCoreNLP-1.1.1.jar 100%[===================>]  26.14M  96.7MB/s    in 0.3s    

2022-03-03 13:09:34 (96.7 MB/s) - ‘VnCoreNLP-1.1.1.jar’ saved [27412575/27412575]

--2022-03-03 13:09:34--

In [14]:
from vncorenlp import VnCoreNLP
rdrsegmenter = VnCoreNLP("/content/vncorenlp/VnCoreNLP-1.1.1.jar", annotators = "wseg", max_heap_size = "-Xmx500m")

In [15]:
senten = "Trường Công nghệ thông tin và Truyền thông, Đại học Bách khoa Hà Nội."
sent = " ".join(rdrsegmenter.tokenize(senten)[0])
sent

'Trường Công_nghệ_thông_tin và Truyền_thông , Đại_học Bách_khoa Hà_Nội .'

In [16]:
len(ques)

260

In [17]:
ques[2]

'Bản sao y bản chính, bản trích sao, bản sao lục được hiểu khác nhau như thế nào theo Quy chế Công tác văn thư của Tập đoàn Dầu khí Việt Nam?'

In [18]:
lst_sent = []

In [19]:
len(ques)

260

In [20]:
sent = rdrsegmenter.tokenize(ques[2])
sent

[['Bản_sao',
  'y',
  'bản_chính',
  ',',
  'bản',
  'trích',
  'sao',
  ',',
  'bản_sao',
  'lục',
  'được',
  'hiểu',
  'khác',
  'nhau',
  'như_thế_nào',
  'theo',
  'Quy_chế',
  'Công_tác',
  'văn_thư',
  'của',
  'Tập_đoàn',
  'Dầu_khí',
  'Việt_Nam',
  '?']]

In [21]:
sent[0]

['Bản_sao',
 'y',
 'bản_chính',
 ',',
 'bản',
 'trích',
 'sao',
 ',',
 'bản_sao',
 'lục',
 'được',
 'hiểu',
 'khác',
 'nhau',
 'như_thế_nào',
 'theo',
 'Quy_chế',
 'Công_tác',
 'văn_thư',
 'của',
 'Tập_đoàn',
 'Dầu_khí',
 'Việt_Nam',
 '?']

In [22]:
for i in range(len(ques)-1):
  sent = rdrsegmenter.tokenize(ques[i])
  lst_sent.append(" ".join(sent[0]))

In [23]:
lst_sent[0]

'Quy_trình , thủ_tục lập hồ_sơ và giao_nộp hồ_sơ , tài_liệu vào Lưu_trữ có được quy_định trong Quy_chế Công_tác văn_thư của Tập_đoàn Dầu_khí Việt_Nam không'

In [24]:
lst_sent[2]

'Bản_sao y bản_chính , bản trích sao , bản_sao lục được hiểu khác nhau như_thế_nào theo Quy_chế Công_tác văn_thư của Tập_đoàn Dầu_khí Việt_Nam ?'

In [25]:
lst_sent[1:5]

['Chỉ có những tổ_chức , cá_nhân thuộc cơ_cấu tổ_chức , quản_lý , điều_hành Cơ_quan PVN thực_hiện công_tác văn_thư mới là đối_tượng áp_dụng Quy_chế Công_tác văn_thư của Tập_đoàn Dầu_khí Việt_Nam đúng không ?',
 'Bản_sao y bản_chính , bản trích sao , bản_sao lục được hiểu khác nhau như_thế_nào theo Quy_chế Công_tác văn_thư của Tập_đoàn Dầu_khí Việt_Nam ?',
 'Chánh Văn_phòng PVN có trách_nhiệm tham_mưu giúp Tổng_giám_đốc PVN quản_lý và chỉ_đạo công_tác văn_thư không ?',
 'Văn_thư Cơ_quan PVN ngoài nhiệm_vụ quản_lý sổ_sách và cơ_sở_dữ_liệu đăng_ký , quản_lý văn_bản còn có những nhiệm_vụ nào khác ?']

In [26]:
len(lst_sent)

259

In [27]:
model_embeddings = model.encode(lst_sent)
model_embeddings

array([[-0.0583247 , -0.03860093, -0.11976992, ...,  0.03184269,
        -0.062165  ,  0.27043983],
       [ 0.05068521, -0.00420728, -0.14195696, ...,  0.02707615,
        -0.13601376,  0.37849498],
       [ 0.05138089, -0.03769527,  0.03546299, ...,  0.09054878,
        -0.08845442,  0.28930372],
       ...,
       [ 0.06001802, -0.10303777, -0.13556878, ..., -0.1502366 ,
        -0.13904196,  0.35420227],
       [-0.12602355, -0.03752872, -0.17815743, ..., -0.02804922,
         0.06094809,  0.25227082],
       [-0.11599098, -0.04771136, -0.15570037, ...,  0.0350916 ,
         0.0222842 ,  0.2187465 ]], dtype=float32)

In [28]:
torch.tensor(model_embeddings).size()

torch.Size([259, 768])

In [29]:
torch.tensor(model_embeddings[0]).size()

torch.Size([768])

In [30]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity 

In [31]:
cosine_similarity([model_embeddings[0]], 
                  model_embeddings[1:5])

array([[0.8633504 , 0.83521277, 0.78285766, 0.83246124]], dtype=float32)

Nhap 1 cau vao 

In [32]:
sent_new = "Có bao nhiêu thành viên là đại diện của Tập đoàn dầu khí trong ủy ban quản lý?"

In [33]:
#Số lượng thành viên là dại diện của Tập đoàn dầu khí trong ủy ban quản lý của các hợp đồng dầu khí trong nước là bao nhiêu?

In [34]:
new_sent_seg = " ".join(rdrsegmenter.tokenize(sent_new)[0])
new_sent_seg

'Có bao_nhiêu thành_viên là đại_diện của Tập_đoàn dầu_khí trong uỷ_ban quản_lý ?'

In [35]:
new_sent_embed = model.encode(new_sent_seg)
new_sent_embed

array([-1.73844025e-01,  8.69712010e-02, -2.75762737e-01, -1.76768094e-01,
       -2.74418630e-02,  6.21127784e-02,  5.99945188e-02,  1.68599755e-01,
        1.93468809e-01,  3.25798750e-01,  1.64438993e-01,  2.14176014e-01,
        1.83039069e-01,  1.35569170e-01, -1.19767459e-02, -8.94343108e-02,
       -3.29979628e-01,  8.26707408e-02,  2.58360039e-02,  5.55081898e-03,
       -3.13848913e-01, -1.72183737e-01,  3.71270150e-01,  8.60746577e-02,
        3.82778883e-01, -3.72533262e-01,  3.17361623e-01, -9.72259268e-02,
       -1.77612193e-02, -2.64951028e-02, -2.32062444e-01,  5.42548038e-02,
        1.03426352e-01,  6.68973625e-02,  3.35439950e-01,  3.47665519e-01,
        1.59095049e-01,  1.63531557e-01, -7.86575675e-02,  4.38326895e-01,
        1.76119044e-01,  1.79328367e-01, -6.90448703e-03, -7.91436806e-02,
        1.06445901e-01, -4.83831801e-02, -1.23130949e-02, -1.73727855e-01,
        2.43543699e-01,  5.17399423e-02,  5.40729687e-02, -6.16881177e-02,
        8.90621319e-02, -

In [36]:
torch.tensor(new_sent_embed).size() 

torch.Size([768])

In [37]:
type(new_sent_embed)

numpy.ndarray

In [38]:
type(model_embeddings)

numpy.ndarray

In [39]:
22*3

66

In [40]:
cosine = cosine_similarity([new_sent_embed],
                  model_embeddings[0:])
cosine

array([[0.7148452 , 0.7596851 , 0.59320104, 0.7739192 , 0.717389  ,
        0.73439443, 0.64313054, 0.68276376, 0.7073809 , 0.7442953 ,
        0.6680783 , 0.8048307 , 0.69835854, 0.7574067 , 0.7187528 ,
        0.7233088 , 0.70106936, 0.7170452 , 0.75183916, 0.69868135,
        0.63258624, 0.67201114, 0.72674286, 0.66217005, 0.7489794 ,
        0.60441905, 0.6996506 , 0.68871593, 0.72453433, 0.64236283,
        0.7217044 , 0.72006553, 0.76858056, 0.71239984, 0.68878484,
        0.6165059 , 0.6832398 , 0.6712618 , 0.7184399 , 0.71234477,
        0.7346095 , 0.7297772 , 0.73814225, 0.69217026, 0.7416713 ,
        0.7976243 , 0.73707503, 0.7121752 , 0.69840896, 0.7639973 ,
        0.7645514 , 0.7142874 , 0.7180016 , 0.74282557, 0.7387895 ,
        0.7166929 , 0.7468889 , 0.7695721 , 0.763967  , 0.69609714,
        0.65123063, 0.6540978 , 0.730022  , 0.7440704 , 0.76204276,
        0.76412725, 0.74299955, 0.75332576, 0.7548306 , 0.74317145,
        0.7433263 , 0.77154684, 0.77144074, 0.73

In [41]:
cosine[0][1]

0.7596851

In [42]:
len(cosine[0])

259

In [43]:
count = 0
top_k = []

for i in range(len(cosine[0])):
  if cosine[0][i] > 0.8:
    count += 1
    top_k.append(cosine[0][i])  
    print("Question: ", ques[i])
    print("Answer: ", ans[i])

Question:  Có bao nhiêu loại văn bản hành chính do PVN ban hành?
Answer:   Theo “Quy chế Công tác văn thư của Tập đoàn Dầu khí Việt Nam” của Tập đoàn Dầu khí Việt Nam • Tại Điều 10 Quy định: “Các loại văn bản hành chính do PVN ban hành bao gồm: nghị quyết, quyết định, chỉ thị, hướng dẫn, thông báo, chương trình, kế hoạch, phương án, đề án, dự án, báo cáo, biên bản, tờ trình, hợp đồng, công văn, bản ghi nhớ, bản cam kết, bản thỏa thuận, giấy chứng nhận, giấy uỷ quyền, giấy mời, giấy giới thiệu, giấy đi đường,  giấy nghỉ phép…”

Question:  Thành viên là đại diện của Tập đoàn dầu khí khi tham gia vào ủy ban quản lý của các hợp đồng dầu khí trong nước có nhiệm vụ gì?
Answer:   Theo Quy chế Quản lý Hợp đồng Dầu khí trong nước của Tập đoàn Dầu khí Việt Nam: Tại Điều 5: Vai trò và nhiệm vụ của thành viên là đại diện của Tập đoàn trong UBQL 1. Là đại diện chính thức của Tập đoàn tham gia UBQL để quản lý, giám sát các hoạt động dầu khí và giải quyết các vấn đề thuộc chức năng của UBQL theo quy 

In [44]:
top_k

[0.8048307,
 0.8717645,
 0.89414907,
 0.830173,
 0.8072419,
 0.8303823,
 0.874635,
 0.868595,
 0.8475522]

In [45]:
count

9